{
  hostname,
  pkgs,
  ...
}:
let

  keybindsModule = import ./keybinds.nix;
  windowrulesModule = import ./windowrules.nix { host = hostname; };
  layoutModule = import ./layout.nix { };

  hostOutputsPath = ./hosts/${hostname}/outputs.nix;
  hostOutputs =
    if builtins.pathExists hostOutputsPath then import hostOutputsPath { host = hostname; } else "";

  hostWindowRulesPath = ./hosts/${hostname}/windowrules.nix;
  hostWindowRules =
    if builtins.pathExists hostWindowRulesPath then
      import hostWindowRulesPath { host = hostname; }
    else
      "";

in
{
  home.packages = with pkgs; [
    niri
    swww
    grim
    slurp
    wl-clip-persist
    cliphist
    wf-recorder
    glib
    wayland
    direnv
    swappy
    xdg-desktop-portal-gnome
    xwayland-satellite
    wineWowPackages.wayland
  ];
  xdg.configFile."niri/config.kdl".text = ''
      // Niri Configuration for ${hostname}
      // Generated by NixOS configuration

      ${hostOutputs}

      ${layoutModule}

      ${keybindsModule}

      ${windowrulesModule}

      ${hostWindowRules}


    environment {
        XDG_CURRENT_DESKTOP "niri"
        MOZ_ENABLE_WAYLAND "1"
        ELECTRON_OZONE_PLATFORM_HINT "wayland"
        QT_QPA_PLATFORM "wayland"
        QT_QPA_PLATFORMTHEME_QT6 "gtk3";
        TERMINAL "wezterm"
        XCURSOR_THEME "Capitaine Cursors (Gruvbox)"
        XCURSOR_SIZE "24"
      }


      hotkey-overlay {
          skip-at-startup
      }

      prefer-no-csd

  '';

  # XWayland satellite service for X11 app support
  systemd.user.services.xwayland-satellite = {
    Unit = {
      Description = "Xwayland outside Wayland";
      BindsTo = "graphical-session.target";
      After = "graphical-session.target";
    };
    Service = {
      Type = "notify";
      NotifyAccess = "all";
      ExecStart = "${pkgs.xwayland-satellite}/bin/xwayland-satellite";
      StandardOutput = "journal";
      Restart = "on-failure";
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };

  # XDG Desktop Portal services - properly configured for screen sharing
  systemd.user.services.xdg-desktop-portal = {
    Unit = {
      Description = "Portal service";
      After = [
        "graphical-session.target"
        "pipewire.service"
      ];
      PartOf = [ "graphical-session.target" ];
    };
    Service = {
      Type = "dbus";
      BusName = "org.freedesktop.portal.Desktop";
      ExecStart = "${pkgs.xdg-desktop-portal}/libexec/xdg-desktop-portal";
      Restart = "on-failure";
      Environment = [
        "XDG_CURRENT_DESKTOP=niri"
        "WAYLAND_DISPLAY=wayland-1"
      ];
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };

  systemd.user.services.xdg-desktop-portal-gnome = {
    Unit = {
      Description = "Portal service (GNOME implementation)";
      After = [
        "graphical-session.target"
        "pipewire.service"
        "xdg-desktop-portal.service"
      ];
      PartOf = [ "graphical-session.target" ];
      Requires = [ "pipewire.service" ];
    };
    Service = {
      Type = "dbus";
      BusName = "org.freedesktop.impl.portal.desktop.gnome";
      ExecStart = "${pkgs.xdg-desktop-portal-gnome}/libexec/xdg-desktop-portal-gnome";
      Restart = "on-failure";
      Environment = [
        "XDG_CURRENT_DESKTOP=niri"
      ];
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };

  systemd.user.services.xdg-desktop-portal-gtk = {
    Unit = {
      Description = "Portal service (GTK/GNOME implementation)";
      After = [
        "graphical-session.target"
        "xdg-desktop-portal.service"
      ];
      PartOf = [ "graphical-session.target" ];
    };
    Service = {
      Type = "dbus";
      BusName = "org.freedesktop.impl.portal.desktop.gtk";
      ExecStart = "${pkgs.xdg-desktop-portal-gtk}/libexec/xdg-desktop-portal-gtk";
      Restart = "on-failure";
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };

  # Place wallpapers in home directory
  home.file = {
    "Pictures/Wallpapers" = {
      source = ../../../wallpapers;
      recursive = true;
    };
  };
}
