# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#b8bb26" } # Gruvbox green for directory paths

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#fabd2f", bold = true, italic = true, underline = true } # Gruvbox yellow
find_position = { fg = "#d3869b", bg = "reset", bold = true, italic = true } # Gruvbox pink

# Marker
marker_copied   = { fg = "#98971a", bg = "#98971a" } # Gruvbox dark green
marker_cut      = { fg = "#fb4934", bg = "#fb4934" } # Gruvbox red
marker_marked   = { fg = "#83a598", bg = "#83a598" } # Gruvbox aqua
marker_selected = { fg = "#fabd2f", bg = "#fabd2f" } # Gruvbox yellow

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "#ebdbb2", bg = "#98971a" } # Gruvbox light gray on dark green
count_cut      = { fg = "#ebdbb2", bg = "#cc241d" } # Gruvbox light gray on dark red
count_selected = { fg = "#ebdbb2", bg = "#fabd2f" } # Gruvbox light gray on yellow

# Border
border_symbol = "│"
border_style  = { fg = "#928374" } # Gruvbox gray

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#928374", bg = "#928374" } # Gruvbox gray

# Mode
mode_normal = { fg = "#ebdbb2", bg = "#458588", bold = true } # Light on blue-gray
mode_select = { fg = "#ebdbb2", bg = "#98971a", bold = true } # Light on green
mode_unset  = { fg = "#ebdbb2", bg = "#cc241d", bold = true } # Light on red

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#458588", bg = "#928374" } # Gruvbox blue on gray
progress_error  = { fg = "#cc241d", bg = "#928374" } # Red on gray

# Permissions
permissions_t = { fg = "#458588" } # Blue-gray
permissions_r = { fg = "#d79921" } # Yellow
permissions_w = { fg = "#cc241d" } # Red
permissions_x = { fg = "#98971a" } # Green
permissions_s = { fg = "#928374" } # Gray

# : }}}


# : Select {{{

[select]
border   = { fg = "#458588" }
active   = { fg = "#d3869b", bold = true } # Pink
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#458588" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border = { fg = "#458588" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#458588" }
title   = {}
hovered = { fg = "#d3869b", underline = true } # Pink

# : }}}


# : Which {{{

[which]
mask            = { bg = "#ebdbb2" } # Light background
cand            = { fg = "#83a598" } # Aqua
rest            = { fg = "#928374" } # Gray
desc            = { fg = "#d3869b" } # Pink
separator       = "  "
separator_style = { fg = "#a89984" } # Brown

# : }}}


# : Help {{{

[help]
on      = { fg = "#83a598" } # Aqua
run     = { fg = "#d3869b" } # Pink
hovered = { reversed = true, bold = true }
footer  = { fg = "#928374", bg = "#3c3836" } # Gray on dark brown

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "#b8bb26" } # Green
title_warn  = { fg = "#fabd2f" } # Yellow
title_error = { fg = "#fb4934" } # Red

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#83a598" }, # Aqua

    # Media
    { mime = "{audio,video}/*", fg = "#fabd2f" }, # Yellow

    # Archives
    { mime = "application/*zip", fg = "#d3869b" }, # Pink
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#d3869b" }, # Pink

    # Documents
    { mime = "application
